export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const PET_LIST_SUCCESS = "PET_LIST_SUCCESS";
export const PET_LIST_REQUEST = "PET_LIST_REQUEST";
export const PET_LIST_FAIL = "PET_LIST_FAIL";